spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB-URL}
    username: ${DB-USER}
    password: ${DB-PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

security.jwt.token:
  secret-key: ${JWT-SECRET-KEY}
  validity: ${JWT-VALIDITY}

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha
  paths-to-match:
    - /api/**
    - /health-check

